security:

    encoders:
       AppBundle\Entity\User:
           algorithm:          sha512
           encode_as_base64:   true
           iterations:         1000

    providers:
        db_provider:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        #login:
            # Below pattern handle /login, /login_check, /registration, /resetting (for the future)
        #    pattern:   ^/(login$|registration|resetting)
        #    anonymous: true

        main:
            pattern:    ^/
            form_login:
                check_path: /login_check
                login_path: /login
                csrf_provider: security.csrf.token_manager
            logout:
                path:   logout
                target: homepage
            anonymous: ~
            security: true
            provider: db_provider

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
